# Generated by Django 4.0.6 on 2023-04-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
