# Generated by Django 4.0.6 on 2023-04-24 20:03

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='private_file',
            field=models.FileField(blank=True, null=True, storage=core.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
